-- SQLite
-- 14
SELECT NAME, LASTNAME, EMAIL FROM CUSTOMERS WHERE STATE = 'SP';

-- 15
SELECT * FROM CARS WHERE STATUS = 'Liberado';

-- 16
SELECT * FROM CARS WHERE YEAR = 2016;

-- 17
SELECT E.NAME, E.PHONE_NUMBER, E.CONTRACT_DATE, P.DESCRIPTION
  FROM EMPLOYEES E JOIN POSITIONS P ON (E.POSITION_ID = P.ID);

-- 18
SELECT E.NAME, COUNT(L.ID) AS 'NUMBER_OF_LOCATIONS'
  FROM EMPLOYEES E JOIN LOCATIONS L ON (L.EMPLOYEE_ID = E.ID)
  GROUP BY E.NAME
  HAVING COUNT(L.ID) >= 2;

-- 19
SELECT C.NAME, COUNT(L.ID) AS 'NUMBER_OF_LOCATIONS'
  FROM CUSTOMERS C JOIN LOCATIONS L ON (L.CUSTOMER_ID = C.ID)
  GROUP BY C.NAME
  HAVING COUNT(L.ID) >= 2;