-- SQLite
-- 20
SELECT L.START_DATE, L.END_DATE, L.TOTAL, C.NAME AS 'CUSTOMER', CR.NAME AS 'CAR', E.NAME AS 'EMPLOYEE' FROM LOCATIONS L
  JOIN CUSTOMERS C ON (L.CUSTOMER_ID = C.ID)
  JOIN CARS CR ON (L.CAR_ID = CR.ID)
  JOIN EMPLOYEES E ON (L.EMPLOYEE_ID = E.ID);

-- 21
SELECT COUNT(ID) AS 'TOTAL_LOCATIONS' FROM LOCATIONS;

-- 22
SELECT *, MAX(TOTAL) AS 'MAX_TOTAL' FROM LOCATIONS;

-- 23
SELECT * FROM LOCATIONS WHERE START_DATE BETWEEN '2022-05-20' AND '2022-12-25';