-- SQLite
-- 09
UPDATE CUSTOMERS SET EMAIL = 'carolina@campuscode.com.br' WHERE ID = 9;

-- 10
UPDATE CUSTOMERS SET BIRTH_DATE = '1986-06-19' WHERE ID = 4;

-- 11
UPDATE CARS SET YEAR = 2019 WHERE ID = 4;

-- 12
DELETE FROM CARS WHERE ID = 2;

-- 13
ALTER TABLE EMPLOYEES RENAME PHONE TO PHONE_NUMBER;

SELECT * FROM CUSTOMERS;
SELECT * FROM CARS;
SELECT * FROM EMPLOYEES;